version: '3'

services:

  wordpress:
    build: ./docker/apache/
    restart: always
    depends_on:
      - mysql
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: mysql
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - loanlamoureux-db:/var/lib/mysql

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      environment:
        PMA_HOST: mysql
      ports:
       - 8181:80

  maildev:
    image: djfarrelly/maildev
    ports:
     - 8282:80

volumes:
  loanlamoureux-db: